Miscellaneous cleanup
d610f20/random-activitygen-py pull request #81
Opened 2020-05-11 10:23 UTC by jenrik

2020-05-11 11:20 UTC, NicEastvillage approved these changes

2020-05-11 13:47 UTC, falkecarlsen approved these changes

2020-05-11 13:51 UTC, falkecarlsen requested changes
Regarding naming, it should be all-lowercase with underscores. I believe this is what was agreed upon in discussion.

This style follows PEP 8: https://www.python.org/dev/peps/pep-0008/#package-and-module-names

2020-05-12 06:33 UTC, falkecarlsen approved these changes

2020-05-12 08:10 UTC, merged